"""rename department

Revision ID: ae3f07567ce5
Revises: fac8a7da04be
Create Date: 2024-07-18 12:15:04.507099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3f07567ce5'
down_revision = 'fac8a7da04be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments','department')
    # ### end Alembic commands ###
